# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(318, 325)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelInput = QtWidgets.QLabel(self.centralWidget)
        self.labelInput.setObjectName("labelInput")
        self.horizontalLayout.addWidget(self.labelInput)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.labelInputSize = QtWidgets.QLabel(self.centralWidget)
        self.labelInputSize.setObjectName("labelInputSize")
        self.horizontalLayout.addWidget(self.labelInputSize)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.plainTextEditInput = QtWidgets.QPlainTextEdit(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(9)
        self.plainTextEditInput.setFont(font)
        self.plainTextEditInput.setTabChangesFocus(True)
        self.plainTextEditInput.setObjectName("plainTextEditInput")
        self.verticalLayout.addWidget(self.plainTextEditInput)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.labelFrom = QtWidgets.QLabel(self.centralWidget)
        self.labelFrom.setObjectName("labelFrom")
        self.gridLayout.addWidget(self.labelFrom, 0, 0, 1, 1)
        self.labelTo = QtWidgets.QLabel(self.centralWidget)
        self.labelTo.setObjectName("labelTo")
        self.gridLayout.addWidget(self.labelTo, 0, 1, 1, 1)
        self.labelPrecision = QtWidgets.QLabel(self.centralWidget)
        self.labelPrecision.setObjectName("labelPrecision")
        self.gridLayout.addWidget(self.labelPrecision, 0, 3, 1, 1)
        self.lineEditBase1 = QtWidgets.QLineEdit(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(9)
        self.lineEditBase1.setFont(font)
        self.lineEditBase1.setObjectName("lineEditBase1")
        self.gridLayout.addWidget(self.lineEditBase1, 1, 0, 1, 1)
        self.lineEditBase2 = QtWidgets.QLineEdit(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(9)
        self.lineEditBase2.setFont(font)
        self.lineEditBase2.setObjectName("lineEditBase2")
        self.gridLayout.addWidget(self.lineEditBase2, 1, 1, 1, 1)
        self.labelBaseRange = QtWidgets.QLabel(self.centralWidget)
        self.labelBaseRange.setObjectName("labelBaseRange")
        self.gridLayout.addWidget(self.labelBaseRange, 1, 2, 1, 1)
        self.lineEditPrecision = QtWidgets.QLineEdit(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(9)
        self.lineEditPrecision.setFont(font)
        self.lineEditPrecision.setObjectName("lineEditPrecision")
        self.gridLayout.addWidget(self.lineEditPrecision, 1, 3, 1, 1)
        self.labelPrecisionRange = QtWidgets.QLabel(self.centralWidget)
        self.labelPrecisionRange.setObjectName("labelPrecisionRange")
        self.gridLayout.addWidget(self.labelPrecisionRange, 1, 4, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelResult = QtWidgets.QLabel(self.centralWidget)
        self.labelResult.setObjectName("labelResult")
        self.horizontalLayout_2.addWidget(self.labelResult)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.labelOutputSize = QtWidgets.QLabel(self.centralWidget)
        self.labelOutputSize.setObjectName("labelOutputSize")
        self.horizontalLayout_2.addWidget(self.labelOutputSize)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.plainTextEditOutput = QtWidgets.QPlainTextEdit(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(9)
        self.plainTextEditOutput.setFont(font)
        self.plainTextEditOutput.setReadOnly(True)
        self.plainTextEditOutput.setObjectName("plainTextEditOutput")
        self.verticalLayout_2.addWidget(self.plainTextEditOutput)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButtonConvert = QtWidgets.QPushButton(self.centralWidget)
        self.pushButtonConvert.setObjectName("pushButtonConvert")
        self.horizontalLayout_3.addWidget(self.pushButtonConvert)
        self.pushButtonSwap = QtWidgets.QPushButton(self.centralWidget)
        self.pushButtonSwap.setObjectName("pushButtonSwap")
        self.horizontalLayout_3.addWidget(self.pushButtonSwap)
        self.pushButtonClear = QtWidgets.QPushButton(self.centralWidget)
        self.pushButtonClear.setObjectName("pushButtonClear")
        self.horizontalLayout_3.addWidget(self.pushButtonClear)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 318, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionHelpGrammar = QtWidgets.QAction(MainWindow)
        self.actionHelpGrammar.setObjectName("actionHelpGrammar")
        self.actionSaveResult = QtWidgets.QAction(MainWindow)
        self.actionSaveResult.setObjectName("actionSaveResult")
        self.menuFile.addAction(self.actionSaveResult)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionHelpGrammar)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.plainTextEditInput, self.lineEditBase1)
        MainWindow.setTabOrder(self.lineEditBase1, self.lineEditBase2)
        MainWindow.setTabOrder(self.lineEditBase2, self.lineEditPrecision)
        MainWindow.setTabOrder(self.lineEditPrecision, self.plainTextEditOutput)
        MainWindow.setTabOrder(self.plainTextEditOutput, self.pushButtonConvert)
        MainWindow.setTabOrder(self.pushButtonConvert, self.pushButtonClear)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NumberConverter"))
        self.labelInput.setText(_translate("MainWindow", "Number:"))
        self.labelInputSize.setText(_translate("MainWindow", "TextLabel"))
        self.labelFrom.setText(_translate("MainWindow", "From:"))
        self.labelTo.setText(_translate("MainWindow", "To:"))
        self.labelPrecision.setText(_translate("MainWindow", "Precision:"))
        self.labelBaseRange.setText(_translate("MainWindow", "(2..36)"))
        self.labelPrecisionRange.setText(_translate("MainWindow", "(0...)"))
        self.labelResult.setText(_translate("MainWindow", "Result:"))
        self.labelOutputSize.setText(_translate("MainWindow", "TextLabel"))
        self.pushButtonConvert.setText(_translate("MainWindow", "Convert"))
        self.pushButtonSwap.setText(_translate("MainWindow", "Swap result"))
        self.pushButtonClear.setText(_translate("MainWindow", "Clear"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionHelpGrammar.setText(_translate("MainWindow", "Grammar"))
        self.actionSaveResult.setText(_translate("MainWindow", "Save result..."))
